### ISSUE TITLE
프론트 깃 & 개발환경 세팅

### ISSUE THREAD

**Issue by captain-yun** [hyunayeo/memo_re_front#1]

**Comment by captain-yun** [comment]
ddd

**Comment by devnabi** [comment]
1. memo_re_front에 Vue.js를 설치하기
![Image](https://github.com/hyunayeo/memo_re_front/assets/114222560/7d3871d3-a7f7-4372-996e-0f1184c2a573)

2. Vue cli 버전을 확인하고 Vue프로젝트를 생성하기 -> Vue버전을 3으로 선택
![Image](https://github.com/hyunayeo/memo_re_front/assets/114222560/6731b375-4569-4f39-8cfb-f6def5d4e224)

**Comment by devnabi** [comment]
Vue.js 3 강의 추천합니다!
[코딩애플 - Vue.js 3 강의](https://youtube.com/playlist?list=PLfLgtT94nNq3Br68sEe26jkOqCPK_8UQ-&si=n8YIjg10Gz9Cdau9)
